server:
  port: 8080
  
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
      - PrefixPath=/
      routes:
      - id: tasks
        uri: lb://tasks
        predicates:
        - Path=/tasks/**
        filters:
        - StripPrefix=1
      - id: users
        uri: lb://users
        predicates:
        - Path=/users/**
        filters:
        - StripPrefix=1