server:
  port: 8090
  
spring:
  application:
    name: users
  datasource:
    url: jdbc:h2:mem:memdb
    username: admin
    password: pass
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
     
    